# Generated by Django 3.1.7 on 2021-04-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210416_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('user_project_view', 'просмотр пользователей!')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
