# Generated by Django 3.1.7 on 2021-04-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210417_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('user_view', 'просмотр пользователей!')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
