# Generated by Django 3.1.7 on 2021-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210417_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='О себе:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на Github:'),
        ),
    ]
