# Generated by Django 3.1.7 on 2021-03-18 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210312_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='list',
            name='summary',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
