# Generated by Django 3.1.7 on 2021-03-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210324_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name='Начало')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Projects',
            },
        ),
    ]
