# Generated by Django 3.1.7 on 2021-03-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210326_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Lists', to='webapp.porjects'),
            preserve_default=False,
        ),
    ]
