# Generated by Django 3.1.7 on 2021-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_list_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_date', models.DateField(verbose_name='Дата Начало')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='Дата Окончания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Projectsd',
            },
        ),
        migrations.AlterField(
            model_name='porjects',
            name='created_date',
            field=models.DateField(verbose_name='Дата Начало'),
        ),
        migrations.AlterField(
            model_name='porjects',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Окончания'),
        ),
        migrations.AlterModelTable(
            name='porjects',
            table=None,
        ),
    ]
