# Generated by Django 3.1.7 on 2021-03-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210327_1302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table=None,
        ),
    ]
