# Generated by Django 3.1.7 on 2021-03-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210327_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lists', to='webapp.projects'),
        ),
    ]
