# Generated by Django 3.1.7 on 2021-03-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210327_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Porjects',
        ),
    ]
