# Generated by Django 3.1.7 on 2021-04-13 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0013_projects_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
    ]
