# Generated by Django 3.1.7 on 2021-04-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210413_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_user_add', 'может добавлть пользователя')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
