# Generated by Django 3.1.7 on 2021-04-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210414_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('user_project_add', 'может добавлть пользователя')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
